name: SaGe Test server
maintainer: Shi Zue
quota: 0
max_results: 10000
graphs:
-
  name: bsbm
  uri: http://example.org/bsbm
  description: DefinitelyAUsefulDescription
  backend: hdt-file
  file: ../SaGe-interface/examples/bsbm1k.hdt
